# Generated by Django 3.2.15 on 2022-08-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('region', models.CharField(blank=True, choices=[], max_length=200, null=True)),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
