# Generated by Django 3.2.15 on 2022-08-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
